package Decor_Puff.Atendente;

import Classes.CPF;
import Classes.Categoria;
import Classes.DAO.ItemDAO;
import Classes.Status_Item;
import Classes.Status_Pedido;
import Classes.Tabelas.Funcionario;
import Classes.Tabelas.Item;
import Classes.Tabelas.Pedido;
import Database.Database;
import Database.Database.TABELAS;
import Database.DatabaseFaker;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaCatalogo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCatalogo.class.getName());
    private int PAGINA_ATUAL = 1;
    private final int ITENS_POR_PAGINA = 25;
    private final int QUANTIDADE_ITENS;
    private final int QUANTIDADE_PAGINAS;
    private final Funcionario funcionario;
    private final DefaultTableModel Model_Catalago;
    private final DefaultTableModel Model_Pedido;
    private Pedido pedido;

    private static Database DB;
    public TelaCatalogo(Database db, Funcionario funcionario) {
        
        DB = db;
        QUANTIDADE_ITENS = DB.getTabela_Tamanho(TABELAS.Item);
        
        QUANTIDADE_PAGINAS = 
                (QUANTIDADE_ITENS % ITENS_POR_PAGINA == 0) ? 
                    QUANTIDADE_ITENS / ITENS_POR_PAGINA : 
                    (QUANTIDADE_ITENS / ITENS_POR_PAGINA) + 1;
        
        initComponents();
        this.btn_Pedidos_Realizados.setVisible(false);
        
        this.funcionario = funcionario;
        this.Model_Catalago = (DefaultTableModel) tab_Catalogo.getModel();        
        this.Model_Pedido = (DefaultTableModel) tab_Pedido.getModel();
        mostrarCatalogo();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btn_Cadastrar_Cliente = new javax.swing.JButton();
        btn_Cadastrar_Produto = new javax.swing.JButton();
        btn_Pedidos_Realizados = new javax.swing.JButton();
        btn_Finalizar_Pedido = new javax.swing.JButton();
        btn_Limpar_Lista = new javax.swing.JButton();
        painel_Catalogo = new javax.swing.JScrollPane();
        tab_Catalogo = new javax.swing.JTable();
        painel_Pedido = new javax.swing.JScrollPane();
        tab_Pedido = new javax.swing.JTable();
        lab_Lista_produtos = new javax.swing.JLabel();
        btn_Voltar_Pg = new javax.swing.JButton();
        btn_Avancar_Pg = new javax.swing.JButton();
        btn_Add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btn_Cadastrar_Cliente.setText("Cadastrar Cliente");
        btn_Cadastrar_Cliente.setActionCommand("CadastrarCliente");
        btn_Cadastrar_Cliente.setPreferredSize(new java.awt.Dimension(160, 24));
        btn_Cadastrar_Cliente.addActionListener(this::btn_Cadastrar_ClienteActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 46, 0, 0);
        getContentPane().add(btn_Cadastrar_Cliente, gridBagConstraints);
        btn_Cadastrar_Cliente.getAccessibleContext().setAccessibleName("CadastrarCliente");

        btn_Cadastrar_Produto.setText("Cadastrar Produto");
        btn_Cadastrar_Produto.setActionCommand("CadastrarProduto");
        btn_Cadastrar_Produto.setPreferredSize(new java.awt.Dimension(160, 24));
        btn_Cadastrar_Produto.addActionListener(this::btn_Cadastrar_ProdutoActionPerformed);
        getContentPane().add(btn_Cadastrar_Produto, new java.awt.GridBagConstraints());
        btn_Cadastrar_Produto.getAccessibleContext().setAccessibleName("CadastrarProduto");

        btn_Pedidos_Realizados.setText("Pedidos Realizados");
        btn_Pedidos_Realizados.setActionCommand("Relatorios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        getContentPane().add(btn_Pedidos_Realizados, gridBagConstraints);

        btn_Finalizar_Pedido.setText("Finalizar Pedido");
        btn_Finalizar_Pedido.setActionCommand("FinalizarPedido");
        btn_Finalizar_Pedido.addActionListener(this::btn_Finalizar_PedidoActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 34, 0, 0);
        getContentPane().add(btn_Finalizar_Pedido, gridBagConstraints);

        btn_Limpar_Lista.setText("Limpar Lista");
        btn_Limpar_Lista.addActionListener(this::btn_Limpar_ListaActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 64, 0, 0);
        getContentPane().add(btn_Limpar_Lista, gridBagConstraints);
        btn_Limpar_Lista.getAccessibleContext().setAccessibleName("LimparLista");

        painel_Catalogo.setPreferredSize(new java.awt.Dimension(800, 600));

        tab_Catalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Categoria", "Qntd", "Descrição", "Venda", "Aluguel", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_Catalogo.setToolTipText("");
        tab_Catalogo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tab_Catalogo.setRowHeight(40);
        tab_Catalogo.setShowGrid(true);
        painel_Catalogo.setViewportView(tab_Catalogo);
        if (tab_Catalogo.getColumnModel().getColumnCount() > 0) {
            tab_Catalogo.getColumnModel().getColumn(0).setMinWidth(50);
            tab_Catalogo.getColumnModel().getColumn(0).setPreferredWidth(50);
            tab_Catalogo.getColumnModel().getColumn(0).setMaxWidth(50);
            tab_Catalogo.getColumnModel().getColumn(1).setResizable(false);
            tab_Catalogo.getColumnModel().getColumn(2).setMinWidth(100);
            tab_Catalogo.getColumnModel().getColumn(2).setPreferredWidth(100);
            tab_Catalogo.getColumnModel().getColumn(2).setMaxWidth(100);
            tab_Catalogo.getColumnModel().getColumn(3).setMinWidth(40);
            tab_Catalogo.getColumnModel().getColumn(3).setPreferredWidth(40);
            tab_Catalogo.getColumnModel().getColumn(3).setMaxWidth(40);
            tab_Catalogo.getColumnModel().getColumn(4).setResizable(false);
            tab_Catalogo.getColumnModel().getColumn(5).setMinWidth(60);
            tab_Catalogo.getColumnModel().getColumn(5).setPreferredWidth(60);
            tab_Catalogo.getColumnModel().getColumn(5).setMaxWidth(60);
            tab_Catalogo.getColumnModel().getColumn(6).setMinWidth(60);
            tab_Catalogo.getColumnModel().getColumn(6).setPreferredWidth(60);
            tab_Catalogo.getColumnModel().getColumn(6).setMaxWidth(60);
            tab_Catalogo.getColumnModel().getColumn(7).setMinWidth(75);
            tab_Catalogo.getColumnModel().getColumn(7).setPreferredWidth(75);
            tab_Catalogo.getColumnModel().getColumn(7).setMaxWidth(75);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 882;
        gridBagConstraints.ipady = 531;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 46, 0, 0);
        getContentPane().add(painel_Catalogo, gridBagConstraints);

        tab_Pedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Categoria", "Quantidade", "Devolução"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_Pedido.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        painel_Pedido.setViewportView(tab_Pedido);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 355;
        gridBagConstraints.ipady = 535;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 45, 0, 0);
        getContentPane().add(painel_Pedido, gridBagConstraints);

        lab_Lista_produtos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lab_Lista_produtos.setText("      Lista de produtos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 94;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 45, 0, 0);
        getContentPane().add(lab_Lista_produtos, gridBagConstraints);

        btn_Voltar_Pg.setText("Voltar");
        btn_Voltar_Pg.addActionListener(this::btn_Voltar_PgActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 88;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 46, 0, 0);
        getContentPane().add(btn_Voltar_Pg, gridBagConstraints);

        btn_Avancar_Pg.setText("Avançar");
        btn_Avancar_Pg.addActionListener(this::btn_Avancar_PgActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 160, 0, 0);
        getContentPane().add(btn_Avancar_Pg, gridBagConstraints);

        btn_Add.setText("Adicionar");
        btn_Add.addActionListener(this::btn_AddActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        getContentPane().add(btn_Add, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_Avancar_PgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Avancar_PgActionPerformed
        
        if (PAGINA_ATUAL < QUANTIDADE_PAGINAS)
        {
            PAGINA_ATUAL += 1;
        }
        mostrarCatalogo();
    }//GEN-LAST:event_btn_Avancar_PgActionPerformed

    private void btn_Voltar_PgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Voltar_PgActionPerformed
        if (PAGINA_ATUAL > 0)
        {
            PAGINA_ATUAL -= 1;
        }
        mostrarCatalogo();
    }//GEN-LAST:event_btn_Voltar_PgActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        
        try {
            
            int[] linhas_selecionadas = tab_Catalogo.getSelectedRows();
            ArrayList<ItemDAO> lista = new ArrayList<ItemDAO>(linhas_selecionadas.length);

            for (int i = 0; i < linhas_selecionadas.length; i++)
            {

                Integer id = (Integer) Model_Catalago.getValueAt(linhas_selecionadas[i], 0);
                Item item = DB.getItem(id);

                if (item.Valor_Aluguel > 0)
                {
                    lista.add(new ItemDAO(item, 1, LocalDateTime.now().plusDays(3)));
                }
                else
                {
                    lista.add(new ItemDAO(item, 1));
                }
            }

            String path = JOptionPane.showInputDialog("Insira o CPF do cliente");

            CPF cpf = new CPF(path);
            var c = DB.getCliente(cpf);

            if (c == null)
            {
                JOptionPane.showMessageDialog(this, "Usuário inexistente!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            else
            {

                this.pedido = new Pedido(0, DB.getCliente(cpf), this.funcionario, LocalDateTime.now(), 50, 25, Status_Pedido.PROCESSANDO, lista);

                Model_Pedido.setRowCount(0);

                for (int j = 0; j < this.pedido.Itens.size(); j++)
                {
                    Model_Pedido.addRow(new Object[]{
                        pedido.Itens.get(j).Item.Nome,
                        pedido.Itens.get(j).Item.Categoria.name(),
                        pedido.Itens.get(j).Quantidade,
                        pedido.Itens.get(j).Data_Devolucao
                    });
                }
            }

        } 
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(this, "Usuário inexistente!", "Erro", JOptionPane.ERROR_MESSAGE);
            System.getLogger(TelaCatalogo.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_Limpar_ListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Limpar_ListaActionPerformed
        Model_Pedido.setRowCount(0);
        this.pedido.Itens.clear();
    }//GEN-LAST:event_btn_Limpar_ListaActionPerformed

    private void btn_Finalizar_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Finalizar_PedidoActionPerformed
        
        for (int i = 0; i < this.pedido.Itens.size(); i++)
        {
            this.pedido.Itens.get(i).Quantidade = (int) Model_Pedido.getValueAt(i, 2);
        }
        
        DB.addPedido(this.pedido);
        
        JOptionPane.showMessageDialog(this, "Pedido realizado!");
        
        this.pedido = null;
        
        Model_Pedido.setRowCount(0);
    }//GEN-LAST:event_btn_Finalizar_PedidoActionPerformed

    private void btn_Cadastrar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cadastrar_ClienteActionPerformed
        
        this.dispose();
        
        TelaCadastrarCliente tela = new TelaCadastrarCliente(DB, funcionario);
        
        tela.setVisible(true);
    }//GEN-LAST:event_btn_Cadastrar_ClienteActionPerformed

    private void btn_Cadastrar_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cadastrar_ProdutoActionPerformed
        this.dispose();
        
        TelaCadastrarProduto tela = new TelaCadastrarProduto(DB, funcionario);
        
        tela.setVisible(true);
    }//GEN-LAST:event_btn_Cadastrar_ProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }
    
    public void mostrarCatalogo()
    {        
        Model_Catalago.setRowCount(0);

        
        int j = 0;
        for (int i = (PAGINA_ATUAL - 1) * ITENS_POR_PAGINA; i < (ITENS_POR_PAGINA * PAGINA_ATUAL) && i < QUANTIDADE_ITENS; i++) {
            
            Item item = DB.getItem(i+1);
              
            Model_Catalago.insertRow(j, new Object[]{
                item.ID,
                item.Nome,
                item.Categoria.name(),
                item.Quantidade,
                item.Descricao,
                item.Valor_Venda,
                item.Valor_Aluguel,
                item.Status.name()
            });
            
            j++;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Avancar_Pg;
    private javax.swing.JButton btn_Cadastrar_Cliente;
    private javax.swing.JButton btn_Cadastrar_Produto;
    private javax.swing.JButton btn_Finalizar_Pedido;
    private javax.swing.JButton btn_Limpar_Lista;
    private javax.swing.JButton btn_Pedidos_Realizados;
    private javax.swing.JButton btn_Voltar_Pg;
    private javax.swing.JLabel lab_Lista_produtos;
    private javax.swing.JScrollPane painel_Catalogo;
    private javax.swing.JScrollPane painel_Pedido;
    private javax.swing.JTable tab_Catalogo;
    private javax.swing.JTable tab_Pedido;
    // End of variables declaration//GEN-END:variables
}

