package Decor_Puff;

import Classes.Cargo;
import Decor_Puff.Atendente.TelaCatalogo;
import Database.*;
import javax.swing.JOptionPane;

public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());
    private static final Database DB = new Database("Database");

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        
        try {
//            for (int i = 0; i < 10; i++) DB.addCliente(DatabaseFaker.Cliente());
//            for (int i = 0; i < 10; i++) DB.addFuncionario(DatabaseFaker.Funcionario());
//            for (int i = 0; i < 10; i++) DB.addItem(DatabaseFaker.Item());
            
        } catch (Exception ex) {
            System.getLogger(TelaLogin.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
            initComponents();
            this.setExtendedState(this.MAXIMIZED_BOTH);
            this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        input_Usuario = new javax.swing.JTextField();
        input_Senha = new javax.swing.JPasswordField();
        lab_Decor_Puf = new javax.swing.JLabel();
        lab_Usuario = new javax.swing.JLabel();
        lab_Senha = new javax.swing.JLabel();
        btn_Entrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Decor Puff - Login");
        setName("Janela"); // NOI18N
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        input_Usuario.setMaximumSize(new java.awt.Dimension(300, 30));
        input_Usuario.setMinimumSize(new java.awt.Dimension(300, 30));
        input_Usuario.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 138;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 139, 0, 140);
        getContentPane().add(input_Usuario, gridBagConstraints);
        input_Usuario.getAccessibleContext().setAccessibleName("input_Usuario");

        input_Senha.setMaximumSize(new java.awt.Dimension(300, 30));
        input_Senha.setMinimumSize(new java.awt.Dimension(300, 30));
        input_Senha.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 138;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 139, 0, 140);
        getContentPane().add(input_Senha, gridBagConstraints);
        input_Senha.getAccessibleContext().setAccessibleName("input_Senha");

        lab_Decor_Puf.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lab_Decor_Puf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_Decor_Puf.setText("DECOR PUF");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 243;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(142, 139, 0, 140);
        getContentPane().add(lab_Decor_Puf, gridBagConstraints);
        lab_Decor_Puf.getAccessibleContext().setAccessibleName("lab_Decor_Puf");

        lab_Usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_Usuario.setText("Usuário");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(119, 139, 0, 0);
        getContentPane().add(lab_Usuario, gridBagConstraints);
        lab_Usuario.getAccessibleContext().setAccessibleName("lab_Usuario");

        lab_Senha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_Senha.setText("Senha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 139, 0, 0);
        getContentPane().add(lab_Senha, gridBagConstraints);
        lab_Senha.getAccessibleContext().setAccessibleName("lab_Senha");

        btn_Entrar.setText("Entrar");
        btn_Entrar.addActionListener(this::btn_EntrarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 306, 74, 140);
        getContentPane().add(btn_Entrar, gridBagConstraints);
        btn_Entrar.getAccessibleContext().setAccessibleName("btn_Entrar");

        getAccessibleContext().setAccessibleName("Frame_TelaLogin");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EntrarActionPerformed
        
        String usuario = input_Usuario.getText();
        String senha = new String(input_Senha.getPassword());
        var funcionario = DB.getFuncionario(usuario, senha);
        
        if (funcionario != null) {
            JOptionPane.showMessageDialog(this, "Login efetuado com sucesso!\nBem-vindo à Decor Puf."); 
            
            if (funcionario.Cargo == Cargo.ATENDENTE)
            {                
                this.dispose();
                TelaCatalogo telacatalogo = new TelaCatalogo(DB, funcionario);
                telacatalogo.setVisible(true);
            }
            
            
        } else {
            JOptionPane.showMessageDialog(this, "Usuário ou senha incorretos!", "Erro de Autenticação", JOptionPane.ERROR_MESSAGE);
            
            input_Usuario.setText("");
            input_Senha.setText("");
            input_Usuario.requestFocus(); 
        }
    }//GEN-LAST:event_btn_EntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Entrar;
    private javax.swing.JPasswordField input_Senha;
    private javax.swing.JTextField input_Usuario;
    private javax.swing.JLabel lab_Decor_Puf;
    private javax.swing.JLabel lab_Senha;
    private javax.swing.JLabel lab_Usuario;
    // End of variables declaration//GEN-END:variables
}
