package Decor_Puff;


import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author maasayoshii
 */
public class TelaCadastrarCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastrarCliente.class.getName());

    /**
     * Creates new form TelaCadastrarCliente
     */
    public TelaCadastrarCliente() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        input_Nome = new javax.swing.JTextField();
        lab_Cadastrar = new javax.swing.JLabel();
        input_Email = new javax.swing.JTextField();
        lab_Nome = new javax.swing.JLabel();
        lab_Email = new javax.swing.JLabel();
        lab_CPF = new javax.swing.JLabel();
        input_CPF = new javax.swing.JFormattedTextField();
        lab_Telefone = new javax.swing.JLabel();
        input_Telefone = new javax.swing.JFormattedTextField();
        btn_Cadastrar = new javax.swing.JButton();
        btn_Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        input_Nome.setMaximumSize(new java.awt.Dimension(300, 30));
        input_Nome.setMinimumSize(new java.awt.Dimension(300, 30));
        input_Nome.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 152, 0, 152);
        getContentPane().add(input_Nome, gridBagConstraints);

        lab_Cadastrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lab_Cadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_Cadastrar.setText("CADASTRAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 1, 0, 0);
        getContentPane().add(lab_Cadastrar, gridBagConstraints);

        input_Email.setMaximumSize(new java.awt.Dimension(300, 30));
        input_Email.setMinimumSize(new java.awt.Dimension(300, 30));
        input_Email.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 152, 0, 152);
        getContentPane().add(input_Email, gridBagConstraints);

        lab_Nome.setText("Nome Completo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 152, 0, 0);
        getContentPane().add(lab_Nome, gridBagConstraints);

        lab_Email.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 152, 0, 0);
        getContentPane().add(lab_Email, gridBagConstraints);

        lab_CPF.setText("CPF:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 152, 0, 0);
        getContentPane().add(lab_CPF, gridBagConstraints);

        try {
            input_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        input_CPF.setMaximumSize(new java.awt.Dimension(300, 30));
        input_CPF.setMinimumSize(new java.awt.Dimension(300, 30));
        input_CPF.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 152, 0, 152);
        getContentPane().add(input_CPF, gridBagConstraints);

        lab_Telefone.setText("Telefone:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 152, 0, 0);
        getContentPane().add(lab_Telefone, gridBagConstraints);

        try {
            input_Telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        input_Telefone.setMaximumSize(new java.awt.Dimension(300, 30));
        input_Telefone.setMinimumSize(new java.awt.Dimension(300, 30));
        input_Telefone.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 152, 0, 152);
        getContentPane().add(input_Telefone, gridBagConstraints);

        btn_Cadastrar.setText("Cadastrar");
        btn_Cadastrar.addActionListener(this::btn_CadastrarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 119, 68, 0);
        getContentPane().add(btn_Cadastrar, gridBagConstraints);

        btn_Voltar.setText("Voltar");
        btn_Voltar.addActionListener(this::btn_VoltarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 152, 68, 0);
        getContentPane().add(btn_Voltar, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed

        String nome = input_Nome.getText().trim();
        String email = input_Email.getText().trim();
        String telefone = input_Telefone.getText();
        String cpf = input_CPF.getText();
        
//        JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos corretamente.", "Aviso", JOptionPane.WARNING_MESSAGE);
//        input_Nome.setText("");
//        input_Email.setText("");
//        input_Telefone.setText("");
//        input_CPF.setText("");
//        input_Nome.requestFocus();
        
        
    }//GEN-LAST:event_btn_CadastrarActionPerformed

    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
        this.dispose();
        
        TelaLogin telalogin = new TelaLogin();
        
        telalogin.setVisible(true);
    }//GEN-LAST:event_btn_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrarCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JButton btn_Voltar;
    private javax.swing.JFormattedTextField input_CPF;
    private javax.swing.JTextField input_Email;
    private javax.swing.JTextField input_Nome;
    private javax.swing.JFormattedTextField input_Telefone;
    private javax.swing.JLabel lab_CPF;
    private javax.swing.JLabel lab_Cadastrar;
    private javax.swing.JLabel lab_Email;
    private javax.swing.JLabel lab_Nome;
    private javax.swing.JLabel lab_Telefone;
    // End of variables declaration//GEN-END:variables
}
