package Decor_Puff.Gerente;

import Decor_Puff.Atendente.*;
import Database.Database;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class TelaCatalogo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCatalogo.class.getName());


    private static Database DB;
    public TelaCatalogo(Database db) {
        DB = db;
        initComponents();
        
        Painel_catalogo.setLayout(new BoxLayout(Painel_catalogo, BoxLayout.Y_AXIS));
        Painel_pedido.setLayout(new BoxLayout(Painel_pedido, BoxLayout.Y_AXIS));
        Painel_catalogo.setAlignmentX(LEFT_ALIGNMENT);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_cadastrar_cliente = new javax.swing.JButton();
        Btn_cadastrar_produto = new javax.swing.JButton();
        Btn_cadastrar_funcionario = new javax.swing.JButton();
        PedidoRealizados = new javax.swing.JButton();
        Btn_finalizar_pedido = new javax.swing.JButton();
        Btn_limpar_lista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Painel_catalogo = new javax.swing.JPanel();
        produto_descricao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Painel_pedido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btn_cadastrar_cliente.setText("Cadastrar Cliente");
        Btn_cadastrar_cliente.setActionCommand("CadastrarCliente");

        Btn_cadastrar_produto.setText("Cadastrar Produto");
        Btn_cadastrar_produto.setActionCommand("CadastrarProduto");

        Btn_cadastrar_funcionario.setText("Cadastrar Funcionario");
        Btn_cadastrar_funcionario.setActionCommand("CadastrarFuncionario");

        PedidoRealizados.setText("Pedidos Realizados");
        PedidoRealizados.setActionCommand("Relatorios");

        Btn_finalizar_pedido.setText("Finalizar Pedido");
        Btn_finalizar_pedido.setActionCommand("FinalizarPedido");

        Btn_limpar_lista.setText("Limpar Lista");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        Painel_catalogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Painel_catalogo.setToolTipText("");

        javax.swing.GroupLayout Painel_catalogoLayout = new javax.swing.GroupLayout(Painel_catalogo);
        Painel_catalogo.setLayout(Painel_catalogoLayout);
        Painel_catalogoLayout.setHorizontalGroup(
            Painel_catalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_catalogoLayout.createSequentialGroup()
                .addComponent(produto_descricao)
                .addGap(761, 761, 761))
        );
        Painel_catalogoLayout.setVerticalGroup(
            Painel_catalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_catalogoLayout.createSequentialGroup()
                .addComponent(produto_descricao)
                .addGap(542, 542, 542))
        );

        jScrollPane1.setViewportView(Painel_catalogo);
        Painel_catalogo.getAccessibleContext().setAccessibleName("CatalogoContent");

        Painel_pedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout Painel_pedidoLayout = new javax.swing.GroupLayout(Painel_pedido);
        Painel_pedido.setLayout(Painel_pedidoLayout);
        Painel_pedidoLayout.setHorizontalGroup(
            Painel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );
        Painel_pedidoLayout.setVerticalGroup(
            Painel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(Painel_pedido);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("      Lista de produtos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_cadastrar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 131, Short.MAX_VALUE)
                        .addGap(70, 70, 70)
                        .addComponent(Btn_cadastrar_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, Short.MAX_VALUE)
                        .addGap(55, 55, 55)
                        .addComponent(Btn_cadastrar_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 157, Short.MAX_VALUE)
                        .addGap(85, 85, 85)
                        .addComponent(PedidoRealizados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Btn_limpar_lista)
                            .addGap(29, 29, 29)
                            .addComponent(Btn_finalizar_pedido))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_cadastrar_cliente)
                    .addComponent(Btn_cadastrar_produto)
                    .addComponent(PedidoRealizados)
                    .addComponent(Btn_cadastrar_funcionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_finalizar_pedido)
                    .addComponent(Btn_limpar_lista))
                .addGap(20, 20, 20))
        );

        Btn_cadastrar_cliente.getAccessibleContext().setAccessibleName("CadastrarCliente");
        Btn_cadastrar_produto.getAccessibleContext().setAccessibleName("CadastrarProduto");
        Btn_cadastrar_funcionario.getAccessibleContext().setAccessibleName("CadastrarFuncionario");
        Btn_limpar_lista.getAccessibleContext().setAccessibleName("LimparLista");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(() -> {Database db = new Database("Database.db"); new TelaCatalogo(db).setVisible(true); });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_cadastrar_cliente;
    private javax.swing.JButton Btn_cadastrar_funcionario;
    private javax.swing.JButton Btn_cadastrar_produto;
    private javax.swing.JButton Btn_finalizar_pedido;
    private javax.swing.JButton Btn_limpar_lista;
    private javax.swing.JPanel Painel_catalogo;
    private javax.swing.JPanel Painel_pedido;
    private javax.swing.JButton PedidoRealizados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel produto_descricao;
    // End of variables declaration//GEN-END:variables
}

