
import Database.Classes.Item;
import Database.Database;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ender
 */
public class TelaCatalogo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCatalogo.class.getName());

    /**
     * Creates new form TelaInicial
     */
    private int itemId;
    private static Database DB;
    public TelaCatalogo(Database db) {
        DB = db;
        initComponents();
        
        Painel_catalogo.setLayout(new BoxLayout(Painel_catalogo, BoxLayout.Y_AXIS));
        Painel_pedido.setLayout(new BoxLayout(Painel_pedido, BoxLayout.Y_AXIS));
        Painel_catalogo.setAlignmentX(LEFT_ALIGNMENT);
        
        adicionar_Produtos();

        System.out.println(Painel_catalogo.getComponentCount());
    }
        
    
   

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_cadastrar_cliente = new javax.swing.JButton();
        Btn_cadastrar_produto = new javax.swing.JButton();
        Btn_cadastrar_funcionario = new javax.swing.JButton();
        PedidoRealizados = new javax.swing.JButton();
        Btn_finalizar_pedido = new javax.swing.JButton();
        Btn_limpar_lista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Painel_catalogo = new javax.swing.JPanel();
        produto_descricao = new javax.swing.JLabel();
        Btn_login = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Painel_pedido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btn_cadastrar_cliente.setText("Cadastrar Cliente");
        Btn_cadastrar_cliente.setActionCommand("CadastrarCliente");
        Btn_cadastrar_cliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Btn_cadastrar_clienteMouseDragged(evt);
            }
        });
        Btn_cadastrar_cliente.addActionListener(this::Btn_cadastrar_clienteActionPerformed);

        Btn_cadastrar_produto.setText("Cadastrar Produto");
        Btn_cadastrar_produto.setActionCommand("CadastrarProduto");
        Btn_cadastrar_produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn_cadastrar_produtoMousePressed(evt);
            }
        });
        Btn_cadastrar_produto.addActionListener(this::Btn_cadastrar_produtoActionPerformed);

        Btn_cadastrar_funcionario.setText("Cadastrar Funcionario");
        Btn_cadastrar_funcionario.setActionCommand("CadastrarFuncionario");
        Btn_cadastrar_funcionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn_cadastrar_funcionarioMousePressed(evt);
            }
        });

        PedidoRealizados.setText("Pedidos Realizados");
        PedidoRealizados.setActionCommand("Relatorios");
        PedidoRealizados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PedidosRealizadosMousePressed(evt);
            }
        });
        PedidoRealizados.addActionListener(this::PedidoRealizadosActionPerformed);

        Btn_finalizar_pedido.setText("Finalizar Pedido");
        Btn_finalizar_pedido.setActionCommand("FinalizarPedido");
        Btn_finalizar_pedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn_finalizar_pedidoMousePressed(evt);
            }
        });
        Btn_finalizar_pedido.addActionListener(this::Btn_finalizar_pedidoActionPerformed);

        Btn_limpar_lista.setText("Limpar Lista");
        Btn_limpar_lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_limpar_listaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn_limpar_listaMousePressed(evt);
            }
        });
        Btn_limpar_lista.addActionListener(this::Btn_limpar_listaActionPerformed);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        Painel_catalogo.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        Painel_catalogo.setToolTipText("");

        javax.swing.GroupLayout Painel_catalogoLayout = new javax.swing.GroupLayout(Painel_catalogo);
        Painel_catalogo.setLayout(Painel_catalogoLayout);
        Painel_catalogoLayout.setHorizontalGroup(
            Painel_catalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_catalogoLayout.createSequentialGroup()
                .addComponent(produto_descricao)
                .addGap(761, 761, 761))
        );
        Painel_catalogoLayout.setVerticalGroup(
            Painel_catalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_catalogoLayout.createSequentialGroup()
                .addComponent(produto_descricao)
                .addGap(542, 542, 542))
        );

        jScrollPane1.setViewportView(Painel_catalogo);
        Painel_catalogo.getAccessibleContext().setAccessibleName("CatalogoContent");

        Btn_login.setText("Login");
        Btn_login.addActionListener(this::Btn_loginActionPerformed);

        Painel_pedido.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        javax.swing.GroupLayout Painel_pedidoLayout = new javax.swing.GroupLayout(Painel_pedido);
        Painel_pedido.setLayout(Painel_pedidoLayout);
        Painel_pedidoLayout.setHorizontalGroup(
            Painel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );
        Painel_pedidoLayout.setVerticalGroup(
            Painel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(Painel_pedido);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("      Lista de produtos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_cadastrar_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addGap(70, 70, 70)
                        .addComponent(Btn_cadastrar_produto, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addGap(55, 55, 55)
                        .addComponent(Btn_cadastrar_funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addGap(85, 85, 85)
                        .addComponent(PedidoRealizados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(Btn_login)
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Btn_limpar_lista)
                                    .addGap(29, 29, 29)
                                    .addComponent(Btn_finalizar_pedido))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_cadastrar_cliente)
                    .addComponent(Btn_cadastrar_produto)
                    .addComponent(PedidoRealizados)
                    .addComponent(Btn_cadastrar_funcionario)
                    .addComponent(Btn_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_finalizar_pedido)
                    .addComponent(Btn_limpar_lista))
                .addGap(20, 20, 20))
        );

        Btn_cadastrar_cliente.getAccessibleContext().setAccessibleName("CadastrarCliente");
        Btn_cadastrar_produto.getAccessibleContext().setAccessibleName("CadastrarProduto");
        Btn_cadastrar_funcionario.getAccessibleContext().setAccessibleName("CadastrarFuncionario");
        Btn_limpar_lista.getAccessibleContext().setAccessibleName("LimparLista");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_limpar_listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_limpar_listaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_limpar_listaActionPerformed

    private void Btn_finalizar_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_finalizar_pedidoActionPerformed
       TelaFinalizarPedido tela = new TelaFinalizarPedido(listaPedidos,DB);
       tela.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Btn_finalizar_pedidoActionPerformed

    private void Btn_cadastrar_clienteMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_cadastrar_clienteMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_cadastrar_clienteMouseDragged

    private void PedidosRealizadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PedidosRealizadosMousePressed
        
    }//GEN-LAST:event_PedidosRealizadosMousePressed

    private void Btn_cadastrar_produtoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_cadastrar_produtoMousePressed
        
    }//GEN-LAST:event_Btn_cadastrar_produtoMousePressed

    private void Btn_cadastrar_funcionarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_cadastrar_funcionarioMousePressed
        TelaCadastrarFuncionario tela = new TelaCadastrarFuncionario(DB);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_cadastrar_funcionarioMousePressed

    private void Btn_limpar_listaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_limpar_listaMousePressed
        Painel_pedido.removeAll();
        Painel_pedido.revalidate();
        Painel_pedido.repaint();
    }//GEN-LAST:event_Btn_limpar_listaMousePressed

    private void Btn_finalizar_pedidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_finalizar_pedidoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_finalizar_pedidoMousePressed

    private void Btn_cadastrar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cadastrar_produtoActionPerformed
        TelaCadastrarProduto tela = new TelaCadastrarProduto(DB);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_cadastrar_produtoActionPerformed

    private void Btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_loginActionPerformed
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_loginActionPerformed

    private void Btn_cadastrar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cadastrar_clienteActionPerformed
        TelaCadastrarCliente tela = new TelaCadastrarCliente(DB);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_cadastrar_clienteActionPerformed

    private void Btn_limpar_listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_limpar_listaMouseClicked
    for (PedidoCarrinho pedido : listaPedidos) {
        for (java.awt.Component comp : Painel_catalogo.getComponents()) {  
            if (comp instanceof ItemCatalogo) {
                ItemCatalogo item = (ItemCatalogo) comp;
                if (item.getNomeProduto().equals(pedido.getNome())) {
                    item.devolverEstoque(1); 
                    break; 
                }
            }
        }
    }
        listaPedidos.clear();
        Painel_pedido.removeAll();
        Painel_pedido.revalidate();
        Painel_pedido.repaint();
    }//GEN-LAST:event_Btn_limpar_listaMouseClicked

    private void PedidoRealizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidoRealizadosActionPerformed
        TelaPedidosRealizados tela = new TelaPedidosRealizados(DB);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PedidoRealizadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(() -> {Database db = new Database("Database.db"); new TelaCatalogo(db).setVisible(true); });
    }
        
    public static class PedidoCarrinho {
        
    private int itemId;
    private String nome;
    private String preco;
    private int quantidade;

    public PedidoCarrinho(
        int id, 
        String nome,
        String preco,
        int quantidade
    ) {
        this.itemId = id;
        this.nome = nome;
        this.preco = preco;
        this.quantidade = quantidade;
    }
    public int getId() {
        return itemId;
    }
    public String getNome() {
        return nome;
    }

    public String getPreco() {
        return preco;
    }

    public int getQuantidade() {
        return quantidade;
    }

    }
    
    private void adicionar_Produtos() {
        Painel_catalogo.removeAll(); 
        ArrayList<Item> produtosDoBanco = DB.listartodososItens();

    //lista os itens do banco de dados
        for (Item item : produtosDoBanco) {
            String precoFormatado = String.format("R$ %.2f", item.Valor);
            String qtdStr = String.valueOf(item.Quantidade);
            String caminhoImagem = "/imagens/mouse.jpeg"; // Imagem padrão temporária

            Painel_catalogo.add(new ItemCatalogo(
                item.ID,
                item.Nome,
                precoFormatado,
                item.Descricao,
                caminhoImagem,
                qtdStr,
                Painel_pedido
            ));
        }
        Painel_catalogo.add(Box.createVerticalStrut(10));
        Painel_catalogo.revalidate();
        Painel_catalogo.repaint();
    }
    public void esconderBotaoLogin() {
    Btn_login.setVisible(false);
    }
    public ArrayList<PedidoCarrinho> listaPedidos =
        new ArrayList<>();

    public class ItemCatalogo extends JPanel {
        private JLabel imagemLabel;
        private JLabel nomeLabel;
        private JLabel precoLabel;
        private JLabel descricaoLabel;
        private JButton botao;
        private JLabel quantidadeLabel;
        private JPanel painelPedido;
    
        public ItemCatalogo(int id,String nome, String preco, String descricao,String caminhoImagem,String quantidade,JPanel painelPedido) {
            
            setAlignmentX(LEFT_ALIGNMENT);
            setLayout(new BorderLayout());
            
            this.painelPedido = painelPedido;
            setPreferredSize(new Dimension(700, 120));

            setMaximumSize(new Dimension(Integer.MAX_VALUE, 120));
            imagemLabel = new JLabel();
            URL url = getClass().getResource(caminhoImagem);

            if(url == null){
            System.out.println("Imagem não encontrada");
            } 
            else{
                ImageIcon icon = new ImageIcon(url);
                Image imagem = icon.getImage().getScaledInstance(100,100,Image.SCALE_SMOOTH);
                imagemLabel.setIcon(new ImageIcon(imagem));
            }
            
          
            ImageIcon icon = new ImageIcon(getClass().getResource(caminhoImagem));
            Image imagem = icon.getImage().getScaledInstance(80,80,Image.SCALE_SMOOTH);
            imagemLabel.setIcon(new ImageIcon(imagem)); 
            JPanel textoPanel = new JPanel();
            textoPanel.setLayout(new BoxLayout(textoPanel,BoxLayout.Y_AXIS));
            
            quantidadeLabel = new JLabel("Quantidade: " + quantidade);
            nomeLabel = new JLabel(nome);
            precoLabel = new JLabel(preco);
            descricaoLabel = new JLabel(descricao);
            botao = new JButton("Adicionar");

            textoPanel.add(nomeLabel);
            textoPanel.add(precoLabel);
            textoPanel.add(descricaoLabel);
            textoPanel.add(quantidadeLabel);
                
           // aqui muda a posição da imagem no catalogo
            add(imagemLabel, BorderLayout.WEST);
            imagemLabel.setBorder(BorderFactory.createEmptyBorder(0, 0, 50, 0));
           //
            
            add(textoPanel, BorderLayout.CENTER);
            
            
            JPanel painelBotao = new JPanel();
            //controle do botão
            botao = new JButton("Adicionar");
            botao.setPreferredSize(new Dimension(100, 40));
            painelBotao.add(botao);
            add(painelBotao, BorderLayout.EAST);
 
            botao.addActionListener(e -> {
            try {
            String textoApenasNumeros = quantidadeLabel.getText().replaceAll("[^0-9]", "");
            int quantidadeAtual = Integer.parseInt(textoApenasNumeros);
            if (quantidadeAtual <= 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Este produto esgotou no catálogo!");
            return; 
            }
            quantidadeAtual--;
            quantidadeLabel.setText("Quantidade: " + quantidadeAtual);
            this.revalidate();
            this.repaint();
            PedidoCarrinho pedido = new PedidoCarrinho(itemId, nome, preco, 1);
            listaPedidos.add(pedido);
        
            JPanel itemPedido = new JPanel();
            itemPedido.setLayout(new BoxLayout(itemPedido, BoxLayout.X_AXIS));
            itemPedido.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
            JLabel item = new JLabel(nome + " - " + preco);
            JButton remover = new JButton("X");
            remover.setPreferredSize(new Dimension(45, 30));
            remover.setMaximumSize(new Dimension(45, 30));

            itemPedido.add(item);
            itemPedido.add(Box.createHorizontalGlue());
            itemPedido.add(remover);
            painelPedido.add(itemPedido);
            painelPedido.revalidate();
            painelPedido.repaint();
        
            remover.addActionListener(rev -> {
            listaPedidos.remove(pedido);
            painelPedido.remove(itemPedido);
            String textoQtdRemover = quantidadeLabel.getText().replaceAll("[^0-9]", "");
            int qtdAoRemover = Integer.parseInt(textoQtdRemover);
            qtdAoRemover++;
            
            quantidadeLabel.setText("Quantidade: " + qtdAoRemover);
            this.revalidate();
            this.repaint();
            painelPedido.revalidate();
            painelPedido.repaint();
            });

            } catch (Exception ex) {
            
            javax.swing.JOptionPane.showMessageDialog(null, "Erro ao processar: " + ex.getMessage());
            }
            });

        
            }
    public void devolverEstoque(int quantidadeParaDevolver) {
        String textoApenasNumeros = quantidadeLabel.getText().replaceAll("[^0-9]", "");
        int quantidadeAtual = Integer.parseInt(textoApenasNumeros);
        quantidadeAtual += quantidadeParaDevolver;
        quantidadeLabel.setText("Quantidade: " + quantidadeAtual);
    
        this.revalidate();
        this.repaint();
    }


    public String getNomeProduto() {
        return nomeLabel.getText();
    }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_cadastrar_cliente;
    private javax.swing.JButton Btn_cadastrar_funcionario;
    private javax.swing.JButton Btn_cadastrar_produto;
    private javax.swing.JButton Btn_finalizar_pedido;
    private javax.swing.JButton Btn_limpar_lista;
    private javax.swing.JButton Btn_login;
    private javax.swing.JPanel Painel_catalogo;
    private javax.swing.JPanel Painel_pedido;
    private javax.swing.JButton PedidoRealizados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel produto_descricao;
    // End of variables declaration//GEN-END:variables
}

