
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.net.URL;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ender
 */
public class TelaInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInicial.class.getName());

    /**
     * Creates new form TelaInicial
     */
    
    public TelaInicial() {
        
        initComponents();
      
       
        Painel_catalogo.setLayout(
        new BoxLayout(Painel_catalogo, BoxLayout.Y_AXIS)
        );

        for(int i = 1; i <= 2; i++) {

        Painel_catalogo.add(
        new ItemCatalogo(
        "Produto",
        "R$ 100",
        "Descrição",
        "/imagens/mouse.jpeg"

        )
        );
        }
        

        Painel_catalogo.revalidate();
        Painel_catalogo.repaint();
        adicionar_Produtos();
        System.out.println(Painel_catalogo.getComponentCount());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_pedido = new javax.swing.JPanel();
        Btn_cadastrar_cliente = new javax.swing.JButton();
        Btn_cadastrar_produto = new javax.swing.JButton();
        Btn_cadastrar_funcionario = new javax.swing.JButton();
        Relatorios = new javax.swing.JButton();
        Btn_finalizar_pedido = new javax.swing.JButton();
        Btn_limpar_lista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Painel_catalogo = new javax.swing.JPanel();
        produto_descricao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Painel_pedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout Painel_pedidoLayout = new javax.swing.GroupLayout(Painel_pedido);
        Painel_pedido.setLayout(Painel_pedidoLayout);
        Painel_pedidoLayout.setHorizontalGroup(
            Painel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );
        Painel_pedidoLayout.setVerticalGroup(
            Painel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        Btn_cadastrar_cliente.setText("Cadastrar Cliente");
        Btn_cadastrar_cliente.setActionCommand("CadastrarCliente");
        Btn_cadastrar_cliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Btn_cadastrar_clienteMouseDragged(evt);
            }
        });

        Btn_cadastrar_produto.setText("Cadastrar Produto");
        Btn_cadastrar_produto.setActionCommand("CadastrarProduto");
        Btn_cadastrar_produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn_cadastrar_produtoMousePressed(evt);
            }
        });
        Btn_cadastrar_produto.addActionListener(this::Btn_cadastrar_produtoActionPerformed);

        Btn_cadastrar_funcionario.setText("Cadastrar Funcionario");
        Btn_cadastrar_funcionario.setActionCommand("CadastrarFuncionario");
        Btn_cadastrar_funcionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn_cadastrar_funcionarioMousePressed(evt);
            }
        });

        Relatorios.setActionCommand("Relatorios");
        Relatorios.setLabel("Relatorios");
        Relatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RelatoriosMousePressed(evt);
            }
        });

        Btn_finalizar_pedido.setText("Finalizar Pedido");
        Btn_finalizar_pedido.setActionCommand("FinalizarPedido");
        Btn_finalizar_pedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn_finalizar_pedidoMousePressed(evt);
            }
        });
        Btn_finalizar_pedido.addActionListener(this::Btn_finalizar_pedidoActionPerformed);

        Btn_limpar_lista.setText("Limpar Lista");
        Btn_limpar_lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn_limpar_listaMousePressed(evt);
            }
        });
        Btn_limpar_lista.addActionListener(this::Btn_limpar_listaActionPerformed);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        Painel_catalogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Painel_catalogo.setToolTipText("");
        Painel_catalogo.setLayout(new javax.swing.BoxLayout(Painel_catalogo, javax.swing.BoxLayout.LINE_AXIS));
        Painel_catalogo.add(produto_descricao);

        jScrollPane1.setViewportView(Painel_catalogo);
        Painel_catalogo.getAccessibleContext().setAccessibleName("CatalogoContent");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(Btn_cadastrar_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(59, 59, 59)
                        .addComponent(Btn_cadastrar_produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(56, 56, 56)
                        .addComponent(Btn_cadastrar_funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31)
                        .addComponent(Relatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(141, 141, 141))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_limpar_lista)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_finalizar_pedido))
                    .addComponent(Painel_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_cadastrar_cliente)
                            .addComponent(Btn_cadastrar_produto)
                            .addComponent(Btn_cadastrar_funcionario)
                            .addComponent(Relatorios))
                        .addGap(25, 25, 25)
                        .addComponent(Painel_pedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_limpar_lista)
                    .addComponent(Btn_finalizar_pedido))
                .addContainerGap())
        );

        Btn_cadastrar_cliente.getAccessibleContext().setAccessibleName("CadastrarCliente");
        Btn_cadastrar_produto.getAccessibleContext().setAccessibleName("CadastrarProduto");
        Btn_cadastrar_funcionario.getAccessibleContext().setAccessibleName("CadastrarFuncionario");
        Btn_limpar_lista.getAccessibleContext().setAccessibleName("LimparLista");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_limpar_listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_limpar_listaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_limpar_listaActionPerformed

    private void Btn_finalizar_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_finalizar_pedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_finalizar_pedidoActionPerformed

    private void Btn_cadastrar_clienteMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_cadastrar_clienteMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_cadastrar_clienteMouseDragged

    private void RelatoriosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RelatoriosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelatoriosMousePressed

    private void Btn_cadastrar_produtoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_cadastrar_produtoMousePressed
        
    }//GEN-LAST:event_Btn_cadastrar_produtoMousePressed

    private void Btn_cadastrar_funcionarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_cadastrar_funcionarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_cadastrar_funcionarioMousePressed

    private void Btn_limpar_listaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_limpar_listaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_limpar_listaMousePressed

    private void Btn_finalizar_pedidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_finalizar_pedidoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_finalizar_pedidoMousePressed

    private void Btn_cadastrar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cadastrar_produtoActionPerformed
        Painel_catalogo.add(
        new ItemCatalogo("Novo Produto", "R$ 100","oi","/imagens/mouse.jpeg")
        );

        Painel_catalogo.revalidate();
        Painel_catalogo.repaint();
    }//GEN-LAST:event_Btn_cadastrar_produtoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInicial().setVisible(true));
    }
    
    private void adicionar_Produtos() {

        Painel_catalogo.add(new ItemCatalogo("Mouse Gamer", "R$ 150","oi","/imagens/mouse.jpeg"));

        Painel_catalogo.add(new ItemCatalogo("Teclado Mecânico", "R$ 300","oi","/imagens/mouse.jpeg"));

        Painel_catalogo.add(new ItemCatalogo("Monitor 24", "R$ 900","oi","/imagens/mouse.jpeg"));

        Painel_catalogo.revalidate();
        Painel_catalogo.repaint();
    }
    public class ItemCatalogo extends JPanel {
        private JLabel imagemLabel;
        private JLabel nomeLabel;
        private JLabel precoLabel;
        private JLabel descricaoLabel;
        private JButton botao;    
    
        public ItemCatalogo(String nome, String preco, String descricao,String caminhoImagem) {
            setLayout(new BorderLayout());

            setMaximumSize(new Dimension(Integer.MAX_VALUE, 120));
            imagemLabel = new JLabel();
            URL url = getClass().getResource("/imagens/mouse.jpeg");

            if(url == null){
                System.out.println("Imagem não encontrada");
            } else {

                ImageIcon icon = new ImageIcon(url);

                Image imagem = icon.getImage().getScaledInstance(
                    100,
                    100,
                    Image.SCALE_SMOOTH
                );

                imagemLabel.setIcon(new ImageIcon(imagem));
            }
            System.out.println(getClass().getResource("/imagens/mouse.jpeg"));
            ImageIcon icon = new ImageIcon(
            getClass().getResource(caminhoImagem)
            );
            Image imagem = icon.getImage().getScaledInstance(
            100,
            100,
            Image.SCALE_SMOOTH
            );
            imagemLabel.setIcon(new ImageIcon(imagem)); 
            
            JPanel textoPanel = new JPanel();
            textoPanel.setLayout(new BoxLayout(
            textoPanel,
            BoxLayout.Y_AXIS
            ));

            nomeLabel = new JLabel(nome);
            precoLabel = new JLabel(preco);
            descricaoLabel = new JLabel(descricao);
            botao = new JButton("Adicionar");

            textoPanel.add(nomeLabel);
            textoPanel.add(precoLabel);
            textoPanel.add(descricaoLabel);

            add(imagemLabel, BorderLayout.WEST);
            add(textoPanel, BorderLayout.CENTER);
            add(botao, BorderLayout.EAST);
        }

        
    }
    
    
    // vi esse codigo para puchar do banco de dados as informações ps:não sei se funciona
   // while(rs.next()) {;;

    //String nome = rs.getString("nome");
    //String preco = rs.getString("preco");
    //String descricao = rs.getString("descricao");
    //Painel_catalogo.add(
       // new Painel_Item_catalogo(nome, preco,descricao)
    //);
    //}  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_cadastrar_cliente;
    private javax.swing.JButton Btn_cadastrar_funcionario;
    private javax.swing.JButton Btn_cadastrar_produto;
    private javax.swing.JButton Btn_finalizar_pedido;
    private javax.swing.JButton Btn_limpar_lista;
    private javax.swing.JPanel Painel_catalogo;
    private javax.swing.JPanel Painel_pedido;
    private javax.swing.JButton Relatorios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel produto_descricao;
    // End of variables declaration//GEN-END:variables
}

