import Database.Classes.Cliente;
import Database.Classes.Funcionario;
import Database.Classes.Item;
import Database.Classes.Pedido;
import Database.Classes.PedidoItem;
import Database.Classes.Utils.CPF;
import Database.Classes.Utils.Status_Pedido;
import Database.Database;
import java.io.ObjectInputFilter.Status;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import org.sqlite.core.DB;

 

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author maasayoshii
 */
public class TelaFinalizarPedido extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaCadastrarCliente
     * @param pedidos
     */private double converterPreco(String preco) {
        return Double.parseDouble(
        preco.replace("R$", "").replace(",", ".").trim()
        );
    }
     private ArrayList<TelaCatalogo.PedidoCarrinho> listaPedidosLocal;
    private double valorTotalGlobal;
    CPF Cpf;
    private static Database DB;
    public TelaFinalizarPedido(ArrayList<TelaCatalogo.PedidoCarrinho> pedidos,Database db) {
    DB = db;
    this.listaPedidosLocal = pedidos;
    initComponents();
    double total = 0;

        for (TelaCatalogo.PedidoCarrinho p : pedidos) {

    JLabel item = new JLabel(
        p.getNome() + " - " + p.getPreco()
    );
    jPanel1.add(item);
    total += converterPreco(p.getPreco());
    }
    this.valorTotalGlobal = total;
    jPanel1.removeAll();
    jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
    JLabel totalLabel = new JLabel( "Total: R$ " + String.format("%.2f", total));

    for (TelaCatalogo.PedidoCarrinho p : pedidos) {
        JLabel item = new JLabel(p.getNome() + " x" + p.getQuantidade() + " - " + p.getPreco());
        jPanel1.add(item);
    }
    jPanel1.add(Box.createVerticalStrut(10));
    jPanel1.add(totalLabel);    
    jPanel1.revalidate();
    jPanel1.repaint();
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Btn_voltar = new javax.swing.JButton();
        ConfirmarPedido = new javax.swing.JButton();
        CPF_label = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane1.setViewportView(jPanel1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Finalizar Pedido");

        Btn_voltar.setText("Voltar");
        Btn_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_voltarMouseClicked(evt);
            }
        });
        Btn_voltar.addActionListener(this::Btn_voltarActionPerformed);

        ConfirmarPedido.setText("Confirmar Pedido");
        ConfirmarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmarPedidoMouseClicked(evt);
            }
        });
        ConfirmarPedido.addActionListener(this::ConfirmarPedidoActionPerformed);

        CPF_label.setMaximumSize(new java.awt.Dimension(300, 30));
        CPF_label.setMinimumSize(new java.awt.Dimension(300, 30));
        CPF_label.setPreferredSize(new java.awt.Dimension(300, 30));
        CPF_label.addActionListener(this::CPF_labelActionPerformed);

        jButton1.setText("OK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CPF_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Btn_voltar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ConfirmarPedido))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPF_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_voltar)
                    .addComponent(ConfirmarPedido))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_voltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_voltarActionPerformed

    private void Btn_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_voltarMouseClicked
        TelaCatalogo tela = new TelaCatalogo(DB);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_voltarMouseClicked

    private void ConfirmarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmarPedidoActionPerformed

    private void ConfirmarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmarPedidoMouseClicked
        
        if(Cpf == null){
            JOptionPane.showMessageDialog(this, "Não tem CPF");
            return;
        }
        if (listaPedidosLocal == null || listaPedidosLocal.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Não há itens no pedido para confirmar!");
            return;
        }
        try {
            Cliente clienteAtual = DB.getCliente(Cpf);//

            if(clienteAtual == null){
                JOptionPane.showMessageDialog(this,
            "Cliente não encontrado!");
            return;
            }

            Funcionario funcionarioAtual = DB.getFuncionario(1);

            if(funcionarioAtual == null){
                JOptionPane.showMessageDialog(this,
                    "Funcionário não encontrado");
                return;
            }
            Pedido novoPedido = new Pedido(
            clienteAtual,
            funcionarioAtual,
            java.time.LocalDateTime.now(),
            10.0,
            10.0,
            valorTotalGlobal,
            Status_Pedido.PROCESSANDO
            );
            
            int idPedidoSalvo = DB.addPedido(novoPedido);

            if (idPedidoSalvo != -1) {
                novoPedido.ID = idPedidoSalvo; 
                for (TelaCatalogo.PedidoCarrinho itemCarrinho : listaPedidosLocal) {
                    Item itemBanco = DB.getItem(itemCarrinho.getId());
                    PedidoItem novoItem = new PedidoItem(
                        novoPedido,
                        itemBanco,
                        itemCarrinho.getQuantidade()
                    );
                    double precoUnitario = converterPreco(itemCarrinho.getPreco());
                    novoItem.Subtotal = precoUnitario * itemCarrinho.getQuantidade();
                    DB.addPedidoItem(novoItem);
                }

                JOptionPane.showMessageDialog(this, "Pedido nº " + idPedidoSalvo + " gravado com sucesso no banco de dados!");
                listaPedidosLocal.clear(); 
                TelaCatalogo catalogo = new TelaCatalogo(DB);
                catalogo.setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao processar o cabeçalho do pedido no banco.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage(), "Erro interno", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_ConfirmarPedidoMouseClicked

    private void CPF_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPF_labelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPF_labelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            Cpf = new CPF(CPF_label.getText().trim());
        } 
        catch(Exception ex) {
            System.getLogger(TelaFinalizarPedido.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(TelaFinalizarPedido.class.getName())
            .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(() -> {
           new TelaFinalizarPedido(new ArrayList<>(),DB).setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_voltar;
    private javax.swing.JTextField CPF_label;
    private javax.swing.JButton ConfirmarPedido;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
